server:
  port: 8080

spring:
  application:
    name: apigateway

  profiles:
    active: loc

  cloud:
    consul:
      enabled: true
      discovery:
        enabled: true
        fail-fast: true
        prefer-ip-address: true
        healthCheckPath: /actuator/health
        register-health-check: true
        health-check-critical-timeout: 5m
        health-check-interval: 30s
        catalog-services-watch-delay: 20000
        heartbeat:
          enabled: false
          ttl-value: 10
        instanceId: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        tags:
          - profile=${spring.profiles.active}
          -
    loadbalancer:
      ribbon:
        enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
          predicates:
            - Path='/api/' + serviceId + '/**','/api/' + serviceId
          filters:
            - name: RewritePath
              args:
                regexp: "'/api/' + serviceId + '/?(?<remaining>.*)'"
                replacement: "'/${remaining}'"
          lower-case-service-id: true


